### ISSUE TITLE
fix: Windows build failing with "illegal token" and syntax errors

### ISSUE THREAD

**Issue by joshhammock** [alnitak/flutter_soloud#292]
After updating to 3.3.0 I'm getting the following errors on build. (The usual warning C4244 lines have been removed)
Flutter doctor and analyze show no issues.

```
Building Windows application...

  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

**************** SOLOUD CONFIGURE.CMAKE
[+] Build dynamic library enabled
[-] Build static library disabled
[-] Build C API disabled
[+] Build MiniAudio enabled
[-] Build demos disabled
[+] NULL backend enabled
[-] SDL2 backend disabled
[-] ALSA backend disabled
[-] CoreAudio backend disabled
[-] OpenSLES backend disabled
[-] XAudio2 backend disabled
[+] WINMM backend enabled
[-] WASAPI backend disabled
[-] Generate Glue disabled
**************** SOLOUD SRC.CMAKE 1
**************** SOLOUD SRC.CMAKE 2  soloud
NO_OPUS_OGG_LIBS has been set. Not linking Opus and Ogg libraries!

H:\flutterApps\project_name\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\audiobuffer.cpp(582,40): error C2589: '(': illegal token on right side of '::' [H:\flutterApps\project_name\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
H:\flutterApps\project_name\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\audiobuffer.cpp(582,40): error C2059: syntax error: ')' [H:\flutterApps\project_name\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]

H:\flutterApps\project_name\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(172,39): error C2589: '(': illegal token on right side of '::' [H:\flutterApps\project_name\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
H:\flutterApps\project_name\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(172,39): error C2059: syntax error: ')' [H:\flutterApps\project_name\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
H:\flutterApps\project_name\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(195,39): error C2589: '(': illegal token on right side of '::' [H:\flutterApps\project_name\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
H:\flutterApps\project_name\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(195,39): error C2059: syntax error: ')' [H:\flutterApps\project_name\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]

Error: Build process failed.

```

**Comment by alnitak** [comment]
Hi @joshhammock, thank you. I think I missed pushing a commit that was fixing that! I will update soon

**Comment by OffhandGames** [comment]
Thank you so much! The interesting thing is that downgrading to a previous version doesn't seem to work either so there may be a dependency that has been upgraded that causes older versions to break as well.

**Comment by abitas** [comment]
Had same problem, but downgrading to 3.1.3 or 3.2.2 fixed it for me.

**Comment by alnitak** [comment]
> Thank you so much! The interesting thing is that downgrading to a previous version doesn't seem to work either so there may be a dependency that has been upgraded that causes older versions to break as well.

@joshhammock probably you have to do a `flutter clean` or maybe manually delete the `build` folder, because the source of that error wasn't present in the previous versions.

**Comment by alnitak** [comment]
Version 3.3.1 should already be available on pub.dev.

Thanks for pointing this out.

**Comment by OffhandGames** [comment]
I can confirm the update works for me. Thanks a ton!

**Comment by abitas** [comment]
Also works for me.
Thanks for rapid response! And thanks a ton for all the work you're putting into this!
