### ISSUE TITLE
fix: Error when run on windows

### ISSUE THREAD

**Issue by docaohuynh** [alnitak/flutter_soloud#309]
**Description**

Error

```bash
C:\source\source\flutter-test\flutter_soloud\example\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(15,33): error C2589: '(': illegal token on right side of '::' [C:\source\source\flutter-test\flutter_soloud\example\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
C:\source\source\flutter-test\flutter_soloud\example\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(15,33): error C2059: syntax error: ')' [C:\source\source\flutter-test\flutter_soloud\example\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
C:\source\source\flutter-test\flutter_soloud\example\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(138,37): error C2589: '(': illegal token on right side of '::' [C:\source\source\flutter-test\flutter_soloud\example\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
C:\source\source\flutter-test\flutter_soloud\example\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(138,37): error C2059: syntax error: 
')' [C:\source\source\flutter-test\flutter_soloud\example\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
C:\source\source\flutter-test\flutter_soloud\example\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(302,37): error C2589: '(': illegal token on right side of '::' [C:\source\source\flutter-test\flutter_soloud\example\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
C:\source\source\flutter-test\flutter_soloud\example\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\audiobuffer\mp3_stream_decoder.cpp(302,37): error C2059: syntax error: 
')' [C:\source\source\flutter-test\flutter_soloud\example\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
```

**Steps To Reproduce**

1. Run example in package flutter_soloud

**Expected Behavior**

Run success

Windows system
Device name	DESKTOP-I778LR7
Processor	AMD Ryzen 5 2600 Six-Core Processor               3.40 GHz
Installed RAM	32.0 GB
Device ID	F76F6CC9-1862-4C67-83A0-4AA3DEFBF14A
Product ID	00331-10000-00001-AA242
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎29/‎2022
OS build	19045.6216
Experience	Windows Feature Experience Pack 1000.19062.1000.0

**Comment by alnitak** [comment]
Ouch, is this happening with the latest 3.3.5 release?

**Comment by docaohuynh** [comment]
@alnitak Yes i just clone latest version
downgrade to flutter_soloud: 3.2.3 it works on windows

**Comment by docaohuynh** [comment]
My project using flutter_soloud: 3.2.3 but when upgrade to 3.3.5 build on windows error like that so i need to downgrade to 3.2.3

**Comment by alnitak** [comment]
It should be fixed with v3.3.6.

**Comment by docaohuynh** [comment]
Tks for quick fix just try v3.3.6 it works on windows
